---
# - hosts: all
#   gather_facts: no
#   tasks:
#     - name: Add python for ansible
#       ansible.builtin.raw: nix-env -i python3

# - hosts: all
#   tasks:
#     - name: Generate hardware configuration
#       shell: nixos-generate-config

- hosts: masters
  tasks:
#     - name: Copy the kubernetes master config
#       copy:
#         src: ./kubernetes/master/kubernetes.nix
#         dest: /etc/nixos/kubernetes.nix
#         owner: root
#         group: root
#         mode: u=rw,g=w,o=r
#     - name: Update the IP address in the config
#       shell: sed -i 's/x.x.x.x/{{ ansible_ssh_host }}/g' /etc/nixos/kubernetes.nix
#     - name: Rebuild the system
#       shell: nixos-rebuild switch
    - name: Reboot host and wait for it to restart
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami


- hosts: masters
  tasks:
    - name: Wait for server to restart
      local_action:
        module: wait_for
          host={{ ansible_ssh_host }}
          port=22
          delay=1
          timeout=300
    - name: Add python for ansible
      ansible.builtin.raw: nix-env -i python3
    - name: Copy the kubeconfig
      shell: mkdir -p .kube && ln -s /etc/kubernetes/cluster-admin.kubeconfig ~/.kube/config
    - name: Verify status
      shell: kubectl get nodes